project_identifier: sponge-docs
base_url: https://api.crowdin.com

files:
  -
    source: '/locale-src/en/LC_MESSAGES/**/*.po'
    translation: '/locale/%locale_with_underscore%/LC_MESSAGES/**/%original_file_name%'
